<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Godot.NET.Sdk/4.4.1">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <RootNamespace>ImpactAlertv3</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="addons\OrbitalPhysics2D\CustomPhysObject\CustomPhysObject.cs" />
    <Content Include="addons\OrbitalPhysics2D\ClassLib\Approacher.cs" />
    <Content Include="addons\OrbitalPhysics2D\RailInterpolator\RailInterpolator.cs" />
    <Content Include="Scripts\ModuleAdapting\Phys2DtoInterpolator.cs" />
    <Content Include="Scripts\ModuleAdapting\Phys2DtoInterpolator.cs.uid" />
    <Content Include="addons\Transform2DInterpolation\Transform2DInterpolation.cs" />
    <Content Include="addons\PhysicsRails2D\PhysicsRails2D.cs" />
    <Content Include="addons\PhysicsRails2D\Nodes\RailNode\RailNode.cs" />
    <Content Include="addons\OrbitalPhysics2D\OrbitalPhysics2D.cs" />
    <Content Include="addons\Transform2DInterpolation\Nodes\InterpolatorNode\InterpolatorNode.cs" />
    <Content Include="addons\Rail2DAutomator\Nodes\AutoRailNode\AutoRailNode.cs" />
    <Content Include="addons\Rail2DAutomator\Nodes\RailAutomator\RailAutomator.cs" />
  </ItemGroup>
</Project>